# Generated by Django 3.2.6 on 2023-05-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiaclinica', '0005_alter_historiaclinica_ultimamodificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAdenda', models.FloatField(blank=True, default=None)),
                ('fechaConsulta', models.DateTimeField(auto_now_add=True)),
                ('motivoConsulta', models.CharField(max_length=50)),
                ('HistoriaClinica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='historiaclinica.historiaclinica')),
            ],
        ),
    ]
