# Generated by Django 3.2.6 on 2023-03-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='edad',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='numHistoriaClinica',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
