# Generated by Django 3.2.6 on 2023-03-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0002_auto_20230317_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='edad',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='numHistoriaClinica',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
