# Generated by Django 3.2.6 on 2023-04-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0004_historiaclinica_ultimamodificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='ultimaModificacion',
            field=models.CharField(max_length=50),
        ),
    ]
