# Generated by Django 3.2.6 on 2023-05-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('historiaclinica', '0005_alter_historiaclinica_ultimamodificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
