# Generated by Django 3.2.6 on 2023-05-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0006_historiaclinica_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='ultimaModificacion',
        ),
    ]
